Coordination service v1
ydb-platform/ydb-java-sdk pull request #93
Opened 2023-04-18 12:13 UTC by KirillKurdyukov

2023-04-23 21:25 UTC, TheKnight commented on topic/src/main/java/tech/ydb/topic/impl/GrpcTopicRpc.java
> -    @Nullable
What about `@NonNull` annotation here?

2023-04-24 09:40 UTC, alex268 requested changes

2023-04-24 09:40 UTC, alex268 commented on coordination/src/main/java/tech/ydb/coordination/CoordinationClient.java
> +    CompletableFuture<LeaderElectionSession> createLeaderElectionSession(SessionSettings settings);
We must not mix low level api and hi level api in one place. We have CoordationClient as the base implementation of the coordination service, and we can have a few helpers as LeaderElection, which use this service, but they aren't a part of the coordination service.

2023-04-24 09:40 UTC, alex268 commented on coordination/src/main/java/tech/ydb/coordination/impl/CoordinationClientImpl.java
> +        final String coordinationNodePath = coordinationRpc.getDatabase() + "/" + settings.getCoordinationNodeName();
I think we must check if client passes the full path of node

2023-04-24 09:40 UTC, alex268 commented on coordination/src/main/java/tech/ydb/coordination/observer/Observer.java
> +    void onNext(SessionResponse sessionResponse);
It's no good to pass our internal classes to client and to force him parse it. I think it is better way - make several methods like onSemaphoreResult, onSemaphoredChanged etc. with empty default implementaion

2023-04-28 16:07 UTC, merged